singleuser_image_repo = "dandiarchive/dandihub"
region = "us-east-1"
singleuser_image_tag = "latest"
jupyterhub_domain = "hub.bican-kb.com"
dandi_api_domain = "https://api.dandiarchive.org"
admin_users = ["kabilar", "dandibot", "yarikoptic"]
profile_list_path = "bican_profiles.yaml"
github_organization = "brain-bican:khub-users"
auth_type = "github"
